export const POLL_FETCH_REQUEST = 'POLL_FETCH_REQUEST';
export const POLL_FETCH_SUCCESS = 'POLL_FETCH_SUCCESS';
export const POLL_FETCH_ERROR = 'POLL_FETCH_ERROR';
export const POLL_SELECT = 'POLL_SEECT';
