export const POLL_FETCH_REQUEST = 'POLL_FETCH_REQUEST';
export const POLL_FETCH_SUCCESS = 'POLL_FETCH_SUCCESS';
export const POLL_FETCH_ERROR = 'POLL_FETCH_ERROR';
export const POLL_SELECT = 'POLL_SELECT';

export const ANSWERS_FETCH_SUCCESS = 'ANSWERS_FETCH_SUCCESS';
export const ANSWERS_FETCH_REQUEST = 'ANSWERS_FETCH_REQUEST';
export const ANSWERS_FETCH_ERROR = 'ANSWERS_FETCH_ERROR';
export const CATEGORY_SET = 'CATEGORY_SET';

export const RESULTS_FETCH_REQUEST = 'RESULTS_FETCH_REQUEST';
export const RESULTS_FETCH_SUCCESS = 'RESULTS_FETCH_SUCCESS';

export const FIND_DEBATE_REQUEST = 'FIND_DEBATE_REQUEST';
export const FIND_DEBATE_SUCCESS = 'FIND_DEBATE_SUCCESS';

export const FIND_SPECTATE_REQUEST = 'FIND_SPECTATE_REQUEST';
export const FIND_SPECTATE_SUCCESS = 'FIND_SPECTATE_SUCCESS';
