export const DEBATES_FETCH_REQUEST = 'DEBATES_FETCH_REQUEST';
export const DEBATES_FETCH_SUCCESS = 'DEBATES_FETCH_SUCCESS';

export const SET_CHATROOM_ID = 'CHATROOM_SET_CHATROOM_ID';
export const DATA_FETCH_SUCCESS = 'CHATROOM_DATA_FETCH_SUCCESS'
export const MESSAGES_FETCH_SUCCESS = 'CHATROOM_MESSAGES_FETCH_SUCCESS';
