export const DEBATES_FETCH_REQUEST = 'DEBATES_FETCH_REQUEST';
export const DEBATES_FETCH_SUCCESS = 'DEBATES_FETCH_SUCCESS';

export const SET_CHATROOM_ID = 'SET_CHATROOM_ID';
export const MESSAGES_FETCH_REQUEST = 'MESSAGES_FETCH_REQUEST';
export const MESSAGES_FETCH_SUCCESS = 'MESSAGES_FETCH_SUCCESS';