export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';

export const IMAGES_FETCH_SUCCESS = 'IMAGE_FETCH_SUCCESS';
export const IMAGE_SELECT = 'IMAGE_SELECT';
