export const ANSWERS_FETCH_SUCCESS = 'ANSWERS_FETCH_SUCCESS';
export const ANSWERS_FETCH_REQUEST = 'ANSWERS_FETCH_REQUEST';
export const ANSWERS_FETCH_ERROR = 'ANSWERS_FETCH_ERROR';

export const ANSWER_SELECT = 'ANSWER_SELECT';
